version: '3.8'

services:
  portal:
    build:
      context: ../portal
    ports:
      - "3000:3000" 
    depends_on:
      - server
      - db
    enivronment:
      - NEXT_PUBLIC_SERVER=http://server:4000/v1
    networks:
      - custom_bridge

  server:
    build:
      context: ../server
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - ../server/.env
    networks:
      - custom_bridge

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - custom_bridge

volumes:
  db_data:

networks:
  custom_bridge:
    driver: bridge
