version: '3.8'

services:
  portal:
    build:
      context: ../portal
    ports:
      - "3000:3000"
    depends_on:
      - server
      - db
    env_file:
      - ../portal/.env

  server:
    build:
      context: ../server
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - ../server/.env

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: